coap_net: additionally provide coap_context_set/get_app_data
obgm/libcoap pull request #1394
Opened 2024-05-14 15:47 UTC by anyc

I somehow missed the documented coap_set/get_app_data functions but found them while adding new coap_context_set/get_app_data functions myself. I think the prefix of the latter would better fit the scheme - like coap_session_set_data and coap_resource_set_userdata. I am fine with using the existing functions now but I thought I send the PR anyways as I already finished it and in case you see a benefit here. If you think this change is not worth the effort, I don't mind if you just close the PR. Thanks!

2024-05-14 15:56 UTC, anyc commented
Maybe renaming it to coap_context_set/get_userdata() would be even better as it fits the naming of other library APIs.

2024-05-14 16:11 UTC, mrdeep1 commented
Only resource uses `userdata `- the rest use `app_data`.  So, I am inclined to stay with `app_data`.

You will need to fix `man/Makefile.am` around line 194 to fix the current build error.

2024-05-14 18:05 UTC, mrdeep1 commented on include/coap3/coap_net.h
>  /**
It would be good if the 2 deprecated functions were documented in `man/coap_deprecated.txt.in` as well.

2024-05-15 08:13 UTC, mrdeep1 requested changes
Documentation tidy up

2024-05-15 08:13 UTC, mrdeep1 commented on man/coap_context.txt.in
> +*void coap_context_set_app_data(coap_context_t *context, void *app_data);*
````
Use _context_ and _app_data_
````

2024-05-15 08:13 UTC, mrdeep1 commented on man/coap_context.txt.in
> +*void *coap_context_get_app_data(const coap_context_t *context);*
````
Use _context_
````

2024-05-15 08:13 UTC, mrdeep1 commented on man/coap_context.txt.in
> +The *coap_context_set_app_data*() function is used to define a _data_ pointer
````
_app_data_, not _data_
````

2024-05-15 08:13 UTC, mrdeep1 commented on man/coap_deprecated.txt.in
> +*void coap_set_app_data(coap_context_t *ctx, void *app_data);*
````
_context_ instead of ctx, _app_data_ instead of app_data
````

2024-05-15 08:13 UTC, mrdeep1 commented on man/coap_deprecated.txt.in
> +*void *coap_get_app_data(const coap_context_t *ctx);*
````
_context_ instead of ctx
````

2024-05-15 08:13 UTC, mrdeep1 commented on man/Makefile.am
>  	@echo ".so man3/coap_deprecated.3" > coap_register_handler.3
Will need to add coap_get_app_data and coap_set_app_data here

2024-05-15 08:13 UTC, mrdeep1 commented on man/coap_deprecated.txt.in
>  *coap_context_get_csm_timeout*() returns the seconds to wait for a (TCP) CSM
Add (sorted order) *coap_context*(3) to SEE ALSO

2024-05-15 11:40 UTC, mrdeep1 requested changes
You may find  `man/examples-code-check man` run under the main libcoap directory helpful here.

2024-05-15 11:40 UTC, mrdeep1 commented on man/coap_deprecated.txt.in
> +
Remove tab from this empty line.

2024-05-15 11:40 UTC, mrdeep1 commented on man/coap_deprecated.txt.in
>  *coap_context_get_csm_timeout*() returns the seconds to wait for a (TCP) CSM
Need to add in return value for `coap_get_app_data`.

2024-05-15 12:02 UTC, anyc commented
Looks like man entries for the deprecated coap_set/get_app_data were missing in the first place. Shall I add them?

2024-05-15 12:13 UTC, mrdeep1 commented
> Looks like man entries for the deprecated coap_set/get_app_data were missing in the first place. Shall I add them?

No need - you have them now documented under coap_deprecated(3).

2024-05-15 12:42 UTC, mrdeep1 commented on man/Makefile.am
>  	@echo ".so man3/coap_deprecated.3" > coap_register_handler.3
You need to add in
````
       @echo ".so man3/coap_deprecated.3" > coap_get_app_data.3
       @echo ".so man3/coap_deprecated.3" > coap_set_app_data.3
````

2024-05-15 14:18 UTC, mrdeep1 approved these changes

2024-05-15 14:19 UTC, mrdeep1 commented
If you could squash all the commits into a single commit, that would be appreciated.

2024-05-15 14:42 UTC, merged